# needs to sperate from mylibrary -api

FROM ubuntu:trusty
MAINTAINER Venkata Santhosh Piduri <santhosh.piduri@gmail.com>

# Prevent dpkg errors
ENV TERM=xterm-256color

# Sed mirror command is used to point to local

RUN apt-get update && \
    apt-get install -y \
    -o APT::Install-Recommend=false -o APT::Install-Suggests=false






