spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mylibrary
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
debug: true
